title: 'Einstellungen Box'
fields:
  -
    handle: show_settings
    field:
      mode: toggle
      input_label: Anzeigen
      type: revealer
      display: Einstellungen
      localizable: false
  -
    handle: background_color
    field:
      options:
        -
          key: primary
          value: 'Primäre Farbe'
        -
          key: secondary
          value: 'Sekundäre Farbe'
      default: secondary
      type: select
      display: Hintergrund
      localizable: false
      if:
        show_settings: 'equals true'
  -
    handle: col_span_mobile
    field:
      options:
        -
          key: 1
          value: '1'
        -
          key: 2
          value: '2'
        -
          key: 3
          value: '3'
        -
          key: 4
          value: '4'
        -
          key: 5
          value: '5'
        -
          key: 6
          value: '6'
      default: '6'
      type: select
      display: 'Spaltenbreite Mobile'
      localizable: false
      width: 50
      if:
        show_settings: 'equals true'
  -
    handle: col_start_mobile
    field:
      options:
        -
          key: 1
          value: '1'
        -
          key: 2
          value: '2'
        -
          key: 3
          value: '3'
        -
          key: 4
          value: '4'
        -
          key: 5
          value: '5'
        -
          key: 6
          value: '6'
      default: '1'
      type: select
      display: 'Startspalte Mobile'
      localizable: false
      width: 50
      if:
        show_settings: 'equals true'
  -
    handle: col_span_desktop
    field:
      options:
        -
          key: 1
          value: '1'
        -
          key: 2
          value: '2'
        -
          key: 3
          value: '3'
        -
          key: 4
          value: '4'
        -
          key: 5
          value: '5'
        -
          key: 6
          value: '6'
        -
          key: 7
          value: '7'
        -
          key: 8
          value: '8'
        -
          key: 9
          value: '9'
        -
          key: 10
          value: '10'
        -
          key: 11
          value: '11'
        -
          key: 12
          value: '12'
      default: '6'
      type: select
      display: 'Spaltenbreite Desktop'
      localizable: false
      width: 50
      if:
        show_settings: 'equals true'
  -
    handle: col_start_desktop
    field:
      options:
        -
          key: 1
          value: '1'
        -
          key: 2
          value: '2'
        -
          key: 3
          value: '3'
        -
          key: 4
          value: '4'
        -
          key: 5
          value: '5'
        -
          key: 6
          value: '6'
        -
          key: 7
          value: '7'
        -
          key: 8
          value: '8'
        -
          key: 9
          value: '9'
        -
          key: 10
          value: '10'
        -
          key: 11
          value: '11'
        -
          key: 12
          value: '12'
      default: '1'
      type: select
      display: 'Startspalte Desktop'
      localizable: false
      width: 50
      if:
        show_settings: 'equals true'
