tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: firstname
            field:
              type: text
              display: Vorname
              localizable: false
              width: 50
          -
            handle: name
            field:
              type: text
              display: Name
              localizable: false
              width: 50
          -
            handle: name_artist_group
            field:
              type: text
              display: 'Name Künstlergruppe'
              localizable: false
          -
            handle: street
            field:
              type: text
              display: 'Strasse / Nr.'
              localizable: false
          -
            handle: zip
            field:
              type: text
              display: PLZ
              localizable: false
              width: 33
          -
            handle: location
            field:
              type: text
              display: Ort
              localizable: false
              width: 66
          -
            handle: phone
            field:
              type: text
              display: Telefon
              localizable: false
          -
            handle: website
            field:
              type: text
              display: Webseite
              localizable: false
          -
            handle: email
            field:
              type: text
              display: E-Mail
              localizable: false
          -
            handle: dob
            field:
              type: date
              display: Geburtsdatum
              localizable: false
          -
            handle: geographic_relation_text
            field:
              type: textarea
              display: Bernbezug
              localizable: false
          -
            handle: work_1_title
            field:
              type: text
              display: 'Werk 1 - Titel'
              localizable: false
              width: 50
          -
            handle: work_1_year
            field:
              type: text
              display: 'Werk 1 - Jahr'
              localizable: false
              width: 50
          -
            handle: work_1_dimensions
            field:
              type: text
              display: 'Werk 1 - Grösse'
              localizable: false
              width: 50
          -
            handle: work_1_duration
            field:
              type: text
              display: 'Werk 1 - Dauer'
              localizable: false
              width: 50
          -
            handle: work_1_technology
            field:
              type: textarea
              display: 'Werk 1 - Technik'
              localizable: false
          -
            handle: work_1_remarks
            field:
              type: textarea
              display: 'Werk 1 - Kommentar'
              localizable: false
          -
            handle: work_2_title
            field:
              type: text
              display: 'Werk 2 - Titel'
              localizable: false
              width: 50
          -
            handle: work_2_year
            field:
              type: text
              display: 'Werk 2 - Jahr'
              localizable: false
              width: 50
          -
            handle: work_2_dimensions
            field:
              type: text
              display: 'Werk 2 - Grösse'
              localizable: false
              width: 50
          -
            handle: work_2_duration
            field:
              type: text
              display: 'Werk 2 - Dauer'
              localizable: false
              width: 50
          -
            handle: work_2_technology
            field:
              type: textarea
              display: 'Werk 2 - Technik'
              localizable: false
          -
            handle: work_2_remarks
            field:
              type: textarea
              display: 'Werk 2 - Kommentar'
              localizable: false
          -
            handle: work_3_title
            field:
              type: text
              display: 'Werk 3 - Titel'
              localizable: false
              width: 50
          -
            handle: work_3_year
            field:
              type: text
              display: 'Werk 3 - Jahr'
              localizable: false
              width: 50
          -
            handle: work_3_dimensions
            field:
              type: text
              display: 'Werk 3 - Grösse'
              localizable: false
              width: 50
          -
            handle: work_3_duration
            field:
              type: text
              display: 'Werk 3 - Dauer'
              localizable: false
              width: 50
          -
            handle: work_3_technology
            field:
              type: textarea
              display: 'Werk 3 - Technik'
              localizable: false
          -
            handle: work_3_remarks
            field:
              type: textarea
              display: 'Werk 3 - Kommentar'
              localizable: false
          -
            handle: document_url
            field:
              type: text
              display: Unterlagen
              localizable: false
              visibility: read_only
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              localizable: false
              validate:
                - required
              visibility: computed
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
              visibility: computed
          -
            handle: parent
            field:
              type: entries
              collections:
                - applications
              max_items: 1
              listable: false
              localizable: true
title: Bewerbungen
